'use client'

import { useState, useRef, useMemo } from 'react'
import { motion, AnimatePresence, useInView } from 'framer-motion'

const faqData = [
  {
    category: 'Location & Logistics',
    icon: '🌏',
    questions: [
      {
        q: 'Why do I need to be a US college student with Asia roots?',
        a: 'This unique combination is central to our program design. US college students bring American business education and perspectives, while Asia roots (Hong Kong, Vietnam, Singapore) mean you have cultural understanding, language skills, and local connections. This dual perspective is invaluable for building products that bridge both markets. Plus, you\'re likely going home for summer anyway!',
      },
      {
        q: 'What counts as "roots" in Asia?',
        a: 'This includes: citizenship or permanent residency, family living there, having grown up there, or strong cultural/language ties. Essentially, you should have the ability to live and work there during summer without visa complications, and ideally have some local network to leverage.',
      },
      {
        q: 'Do I need to physically be in Asia during summer?',
        a: 'Yes, absolutely. The Summer Capstone (May-August) requires you to be on-ground in one of our hub cities: Hong Kong, Ho Chi Minh City, Hanoi, or Singapore. You\'ll be building and running programs locally, meeting customers face-to-face, and leading your Brand Ambassador team in person.',
      },
      {
        q: 'Can the spring phase be done fully remote from my US campus?',
        a: 'Yes! Spring Shadowing (January-April) is designed to be fully remote, working around your US class schedule. All meetings, trainings, and deliverables can be completed from anywhere with good internet.',
      },
      {
        q: 'What if I\'m not from one of the four hub cities?',
        a: 'If you\'re from a nearby area (e.g., Kuala Lumpur, Manila, Shenzhen), reach out to discuss. We may be able to accommodate other locations depending on logistics, but our primary support infrastructure is in HK, HCMC, Hanoi, and Singapore.',
      },
    ],
  },
  {
    category: 'Program',
    icon: '📚',
    questions: [
      {
        q: 'What exactly will I be doing during the Spring Shadowing phase?',
        a: 'During Spring (January-April), you\'ll shadow MLV\'s Operations Leads remotely from your US campus. This includes attending team meetings, helping with customer acquisition research, shadowing speaker outreach, and assisting with Summer Ignite preparation. It\'s designed to give you a 360° view of how a startup operates before you build your own.',
      },
      {
        q: 'How is the Summer Capstone different from a traditional internship?',
        a: 'Unlike traditional internships where you work on assigned tasks, the Summer Capstone has you building and launching your own initiative under MLV\'s umbrella. You\'ll be on-ground in Asia, leading a team of Brand Ambassadors, and going through the full entrepreneurial journey - customer discovery, MVP building, marketing, and actually acquiring paying customers.',
      },
      {
        q: 'What kind of initiative will I be building in the summer?',
        a: 'You\'ll build an entrepreneurial project for students in your city. The exact format (workshop, course, camp, community, etc.) will be determined by your customer research during May. You\'ll have creative freedom to design something that solves a real problem for students in your market, with MLV\'s brand and resources behind you.',
      },
      {
        q: 'What are the two phases and how do they connect?',
        a: 'Phase 1 (Spring Shadowing, Jan-Apr): Remote learning - shadow Operations Leads, understand MLV\'s business model, help with existing programs. Phase 2 (Summer Capstone, May-Aug): Full-time on-ground - build and launch your own project in Asia. Spring prepares you with skills and context; summer is where you apply them.',
      },
    ],
  },
  {
    category: 'Compensation',
    icon: '💰',
    questions: [
      {
        q: 'Why is the spring phase unpaid?',
        a: 'Spring is designed as a learning experience, similar to how business schools charge tuition. You\'re gaining real startup education that would cost thousands at an accelerator program. The ROI comes from the skills you build and the paid summer opportunity.',
      },
      {
        q: 'How does the revenue share work in summer?',
        a: 'You\'ll receive 5-10% of the revenue generated by your initiative, based on your contribution level. This is determined by factors like customer acquisition, program delivery quality, and overall impact. Top performers can earn several thousand dollars.',
      },
      {
        q: 'What if my program doesn\'t generate revenue?',
        a: 'We\'ve designed the program with guardrails to maximize your chances of success. You\'ll have mentorship, resources, and a proven playbook. That said, entrepreneurship involves risk - but even if revenue is lower than expected, the learning experience and portfolio piece are invaluable.',
      },
    ],
  },
  {
    category: 'Requirements',
    icon: '✅',
    questions: [
      {
        q: 'Do I need prior startup experience?',
        a: 'No! We\'re looking for potential, not experience. If you\'ve never worked at a startup but have shown initiative in other ways (side projects, club leadership, etc.), you could be a great fit. What matters is your drive to learn and build.',
      },
      {
        q: 'What year in university should I be?',
        a: 'We accept students from any year, including incoming freshmen and those about to graduate. What matters most is your availability during the program period and your commitment level.',
      },
      {
        q: 'I\'m not a business major. Can I still apply?',
        a: 'Absolutely! Some of the best entrepreneurs come from non-business backgrounds. Engineers, designers, social scientists, and liberal arts majors all bring unique perspectives. We value diverse backgrounds.',
      },
      {
        q: 'What if I can\'t commit 20-30 hours/week in summer?',
        a: 'The summer phase is intensive by design - you\'re running a real business. If you have other major commitments (another internship, summer school), this might not be the right timing. We\'re happy to consider you for future cohorts.',
      },
    ],
  },
  {
    category: 'Application',
    icon: '📝',
    questions: [
      {
        q: 'When is the application deadline?',
        a: 'Applications for the 2026 cohort will close in late 2025. Exact dates will be announced soon. We recommend applying early as we review applications on a rolling basis.',
      },
      {
        q: 'How competitive is the program?',
        a: 'We\'re selective but not exclusionary. We look for demonstrated drive and potential over perfect credentials. Strong candidates show initiative, curiosity, and a clear interest in entrepreneurship.',
      },
      {
        q: 'What makes a strong video introduction?',
        a: 'Be yourself! We want to see the real you, not a polished corporate presentation. Tell us why you\'re excited about startups, share a story about a time you showed initiative, and let your personality come through. Keep it under 2 minutes.',
      },
      {
        q: 'Will I hear back if I\'m rejected?',
        a: 'Yes, we notify all applicants of our decision. Unfortunately, we can\'t provide detailed feedback due to volume, but we encourage reapplication in future cohorts.',
      },
    ],
  },
  {
    category: 'Other',
    icon: '💡',
    questions: [
      {
        q: 'Can I participate if I have other commitments?',
        a: 'Spring is designed to work around classes (5-8 hrs/week). Summer is more intensive. If you have another part-time commitment, it might work - let\'s discuss your specific situation during the interview.',
      },
      {
        q: 'What happens after the program ends?',
        a: 'Many alumni continue their initiatives beyond the program, with ongoing support from MLV. Others use the experience to launch into startup careers, consulting, or top MBA programs. You\'ll also join our alumni network for lifelong connections.',
      },
      {
        q: 'Who can I contact with more questions?',
        a: 'Reach out to Tim Liu at tim@mlvstudent.com or connect on LinkedIn. We\'re happy to answer any questions not covered here.',
      },
    ],
  },
]

// FAQ Item Component
function FAQItem({
  question,
  answer,
  isOpen,
  onToggle,
  index,
}: {
  question: string
  answer: string
  isOpen: boolean
  onToggle: () => void
  index: number
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ delay: index * 0.05 }}
      className="border-b border-gray-800 last:border-0"
    >
      <button
        onClick={onToggle}
        className="w-full py-5 flex items-center justify-between text-left group"
      >
        <span className={`text-lg font-medium transition-colors ${isOpen ? 'text-white' : 'text-gray-300 group-hover:text-white'}`}>
          {question}
        </span>
        <motion.div
          animate={{ rotate: isOpen ? 45 : 0 }}
          transition={{ duration: 0.2 }}
          className={`flex-shrink-0 ml-4 w-8 h-8 rounded-full flex items-center justify-center transition-colors ${
            isOpen ? 'bg-primary text-white' : 'bg-dark-lighter text-gray-400 group-hover:bg-primary/20'
          }`}
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
        </motion.div>
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <p className="pb-5 text-gray-400 leading-relaxed">{answer}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  )
}

export default function FAQ() {
  const [searchQuery, setSearchQuery] = useState('')
  const [openItems, setOpenItems] = useState<Set<string>>(new Set())
  const [activeCategory, setActiveCategory] = useState<string | null>(null)
  const sectionRef = useRef(null)

  const toggleItem = (id: string) => {
    setOpenItems((prev) => {
      const newSet = new Set(prev)
      if (newSet.has(id)) {
        newSet.delete(id)
      } else {
        newSet.add(id)
      }
      return newSet
    })
  }

  // Filter FAQs based on search query
  const filteredFAQs = useMemo(() => {
    if (!searchQuery.trim()) {
      return activeCategory
        ? faqData.filter((cat) => cat.category === activeCategory)
        : faqData
    }

    const query = searchQuery.toLowerCase()
    return faqData
      .map((category) => ({
        ...category,
        questions: category.questions.filter(
          (q) =>
            q.q.toLowerCase().includes(query) ||
            q.a.toLowerCase().includes(query)
        ),
      }))
      .filter((category) => category.questions.length > 0)
  }, [searchQuery, activeCategory])

  return (
    <section
      id="faq"
      ref={sectionRef}
      className="section-padding relative overflow-hidden"
    >
      {/* Background */}
      <div className="absolute inset-0 bg-dark" />
      <div className="absolute inset-0 bg-grid-pattern opacity-30" />

      {/* Gradient orbs */}
      <div className="absolute top-1/4 -right-40 w-[500px] h-[500px] bg-primary/5 rounded-full blur-3xl" />
      <div className="absolute bottom-1/4 -left-40 w-[400px] h-[400px] bg-accent-cyan/5 rounded-full blur-3xl" />

      <div className="container-custom relative z-10">
        {/* Section header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="text-center mb-12"
        >
          <span className="text-primary text-sm font-semibold uppercase tracking-widest mb-4 block">
            Got Questions?
          </span>
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
            <span className="text-white">Frequently Asked </span>
            <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-gray-400 text-lg max-w-3xl mx-auto">
            Everything you need to know about the MLV PMA program. Can&apos;t find what
            you&apos;re looking for? Reach out to us directly.
          </p>
        </motion.div>

        {/* Search bar */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-xl mx-auto mb-8"
        >
          <div className="relative">
            <svg
              className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <input
              type="text"
              placeholder="Search questions..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-12 pr-4 py-4 bg-dark-lighter border border-gray-800 rounded-2xl text-white placeholder-gray-500 focus:outline-none focus:border-primary transition-colors"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-500 hover:text-white transition-colors"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            )}
          </div>
        </motion.div>

        {/* Category filters */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="flex flex-wrap justify-center gap-3 mb-12"
        >
          <button
            onClick={() => setActiveCategory(null)}
            className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
              !activeCategory
                ? 'bg-primary text-white'
                : 'bg-dark-lighter text-gray-400 hover:text-white'
            }`}
          >
            All
          </button>
          {faqData.map((category) => (
            <button
              key={category.category}
              onClick={() => setActiveCategory(category.category)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-all flex items-center gap-2 ${
                activeCategory === category.category
                  ? 'bg-primary text-white'
                  : 'bg-dark-lighter text-gray-400 hover:text-white'
              }`}
            >
              <span>{category.icon}</span>
              {category.category}
            </button>
          ))}
        </motion.div>

        {/* FAQ List */}
        <div className="max-w-3xl mx-auto">
          {filteredFAQs.length === 0 ? (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center py-12"
            >
              <div className="text-4xl mb-4">🔍</div>
              <p className="text-gray-400">No questions found matching your search.</p>
              <button
                onClick={() => setSearchQuery('')}
                className="mt-4 text-primary hover:text-primary-light transition-colors"
              >
                Clear search
              </button>
            </motion.div>
          ) : (
            filteredFAQs.map((category) => (
              <motion.div
                key={category.category}
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                viewport={{ once: true }}
                className="mb-8"
              >
                {/* Category header */}
                <div className="flex items-center gap-3 mb-4">
                  <span className="text-2xl">{category.icon}</span>
                  <h3 className="text-xl font-semibold text-white">{category.category}</h3>
                </div>

                <div className="glass-card px-6">
                  {category.questions.map((item, qIndex) => (
                    <FAQItem
                      key={item.q}
                      question={item.q}
                      answer={item.a}
                      isOpen={openItems.has(`${category.category}-${qIndex}`)}
                      onToggle={() => toggleItem(`${category.category}-${qIndex}`)}
                      index={qIndex}
                    />
                  ))}
                </div>
              </motion.div>
            ))
          )}
        </div>

        {/* Still have questions */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.3 }}
          className="mt-16 text-center"
        >
          <div className="glass-card inline-flex flex-col sm:flex-row items-center gap-4 px-8 py-6">
            <div className="text-3xl">💬</div>
            <div className="text-left">
              <p className="text-white font-medium">Still have questions?</p>
              <p className="text-gray-400 text-sm">
                Reach out to Tim Liu at{' '}
                <a href="mailto:tim@mlvstudent.com" className="text-primary hover:text-primary-light">
                  tim@mlvstudent.com
                </a>
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
